name: Deploy Java Application to Tomcat

on:
  push:
    branches:
      - main  # Change this to your deployment branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Java
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '11'  # Change to your Java version

      # Step 3: Build the project
      - name: Build with Maven
        run: mvn clean package
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

        

            
